print("This is a triangle calculator")
b = int(input("Please enter the base of the triangle: "))
h = int(input("Please enter the height of the triangle: "))
a = b * h * (1 / 2)
print("The triangle's area is", a)
